### ISSUE TITLE
Use Flask-Login to manage user sessions

### ISSUE THREAD

**Issue by fsiddi** [armadillica/pillar-web#1]
Currently we use our own implementation, but I think it would be simpler to just use Flask-Login to store all relevant info into a User object. This makes keeping the user authenticated easier as well.

**Comment by fsiddi** [comment]
This has been implemented, but currently it still seem to cause infinite redirect loops when the token expires (maybe because the user logged in via another browser). Needs some investigation. Do you have time for this @Eibriel?

**Comment by Eibriel** [comment]
I'll take a look!

**Comment by Eibriel** [comment]
I can't reproduce it, I'll need some Log Output

**Comment by Eibriel** [comment]
@fsiddi I've reproduced the error by accidentally trying to authenticate against blender.org/id (instead of my local BlenderID server) using tokens stored on my local BlenderID server.

Maybe that is what happened to you? In that case the workaround is logout entering http://127.0.0.1:5001/users/logout

**Comment by fsiddi** [comment]
Fixed by switching to Flask-Login.
